// GENERATED by scripts/content/build-lsbd-org-import.mjs from content/lsbd-org/*.json.
// Documents carried over from www.lsbd.org (scraped 2026-10-02) that pages link
// directly. The files are in public/documents/.

export interface DocumentLink {
  label: string;
  href: string;
  bytes: number;
}

export interface RulemakingProceeding {
  /** Date the summary report was sent, as stated on lsbd.org (YYYY-MM-DD). */
  date: string;
  title: string;
  description: string;
  documents: DocumentLink[];
}

export const RULEMAKING_HISTORY: RulemakingProceeding[] = [
  {
    "date": "2025-10-10",
    "title": "Rules 1709, 1711, 1713",
    "description": "§1709. Examination of Dentists; §1711. Examination of Dental Hygienists; §1713. Board Approved Regionla or National Independent Third Party Clinical Examinations. Summary report sent: October 10, 2025. Legislative Oversight Committee report: N/A. Effective December 20, 2025.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi1709-1711-1713.pdf",
        "bytes": 654009
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr251010.pdf",
        "bytes": 5810208
      }
    ]
  },
  {
    "date": "2025-06-20",
    "title": "Rule 136",
    "description": "§136. Dental Records. Summary report sent: June 20, 2025. Legislative Oversight Committee report: N/A. Effective August 20, 2025.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi136.pdf",
        "bytes": 674519
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr250610.pdf",
        "bytes": 5809701
      }
    ]
  },
  {
    "date": "2025-02-10",
    "title": "Rules 128, 1611, 1613, 1709, 1711",
    "description": "§128. Provisional Licensure for Dental Healthcare Workers Providing Gratuitous Services; §1611. Continuing Education Requirements for Relicensure of Dentists; §1613. Continuing Education Requirements for Relicensure of Dental Hygienists; §1709. Examination of Dentists; §1711. Examination of Dental Hygienists. Summary report sent: February 10, 2025. Legislative Oversight Committee report: N/A. Effective June 20, 2025.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi128-1611-1613-1709-1711.pdf",
        "bytes": 673594
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr250210.pdf",
        "bytes": 5816998
      }
    ]
  },
  {
    "date": "2024-03-13",
    "title": "Rule 313",
    "description": "§313 Portable and Mobile Dentistry. Summary report sent: March 13, 2024. Legislative Oversight Committee report: N/A. Effective May 20, 2024.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi313.pdf",
        "bytes": 567827
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr240313.pdf",
        "bytes": 196938
      }
    ]
  },
  {
    "date": "2023-12-12",
    "title": "Rule 1611",
    "description": "§1611 Continuing Education Requirements for Relicensure of Dentists. Summary report sent: December 12, 2023. Legislative Oversight Committee report: N/A. Effective February 20, 2024.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi1611.pdf",
        "bytes": 539551
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr231212.pdf",
        "bytes": 198583
      }
    ]
  },
  {
    "date": "2023-06-12",
    "title": "Rules 122, 301",
    "description": "§122 Scopes of Practice; §301 Advertising and Soliciting by Dentists. Summary report sent: June 12, 2023. Legislative Oversight Committee report: N/A. Effective August 20, 2023.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi122-301.pdf",
        "bytes": 533052
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr230612.pdf",
        "bytes": 210230
      }
    ]
  },
  {
    "date": "2022-11-10",
    "title": "Rules 103, 306, 706, 710",
    "description": "§103 Evidence of Graduation; §306 Requirements of Applicants for Dental Licensure by Credentials; §706 Requirements of Applicants for Licensure by Credentials (Hygienists); §710 Administration of Local Anesthesia for Dental Purposes. Summary report sent: November 10, 2022. Legislative Oversight Committee report: N/A. Effective January 20, 2023.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi103-306-706-710.pdf",
        "bytes": 541426
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr221110.pdf",
        "bytes": 287240
      }
    ]
  },
  {
    "date": "2022-08-10",
    "title": "Rules 322, 1607",
    "description": "§322 Expungement of Disciplinary Actions; §1607 Exemptions. Summary report sent: August 10, 2022. Legislative Oversight Committee report: N/A. Effective September 20, 2022.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi322-1607.pdf",
        "bytes": 611308
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr220810.pdf",
        "bytes": 287381
      }
    ]
  },
  {
    "date": "2022-08-10",
    "title": "Rule 702",
    "description": "§702 General Supervision in Nursing Homes. Summary report sent: August 10, 2022. Legislative Oversight Committee report: N/A. Effective October 20, 2022.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi702.pdf",
        "bytes": 712778
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr220810b.pdf",
        "bytes": 279444
      }
    ]
  },
  {
    "date": "2021-12-20",
    "title": "Rules 120, 306, 419",
    "description": "§120 Temporary Licenses and Permits Pending Normal Licenses; §306 Requirements of Applicants for Dental Licensure by Credentials; §419 Licenses, Permits and Examinations (Dental Hygienists). Summary report sent: December 20, 2021. Legislative Oversight Committee report: N/A. Effective February 20, 2022.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi120-306-419.pdf",
        "bytes": 629466
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr211220.pdf",
        "bytes": 335855
      }
    ]
  },
  {
    "date": "2021-08-11",
    "title": "Rule 1615",
    "description": "§1615 Approved Courses. Summary report sent: August 11, 2021. Legislative Oversight Committee report: N/A. Effective October 20, 2021.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi1615.pdf",
        "bytes": 597909
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr210811.pdf",
        "bytes": 284604
      }
    ]
  },
  {
    "date": "2020-12-14",
    "title": "Rules 203, 701",
    "description": "§203 Teledentistry; §701 Authorized Duties. Summary report sent: December 14, 2020. Legislative Oversight Committee report: N/A. Effective February 20, 2021.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi203-701.pdf",
        "bytes": 170614
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr201214.pdf",
        "bytes": 222210
      }
    ]
  },
  {
    "date": "2020-10-12",
    "title": "Rules 322, 1502",
    "description": "§322 Expungement of Disciplinary Actions; §1502 Types of Permits. Summary report sent: October 12, 2020. Legislative Oversight Committee report: N/A. Effective January 20, 2021.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi322-1502.pdf",
        "bytes": 141370
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr201012.pdf",
        "bytes": 227367
      }
    ]
  },
  {
    "date": "2020-06-08",
    "title": "Rule 105",
    "description": "§105 Restricted Licensees. Summary report sent: June 8, 2020. Legislative Oversight Committee report: N/A. Effective July 20, 2020.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi105.pdf",
        "bytes": 116628
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr200608.pdf",
        "bytes": 358688
      }
    ]
  },
  {
    "date": "2019-10-14",
    "title": "Rules 1503, 1607, 1615",
    "description": "§1503 Personal Permits for Sedation/Anesthesia; §1607 Exemptions; §1615 Approved Courses. Summary report sent: October 14, 2019. Legislative Oversight Committee report: N/A. Effective December 20, 2019.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi1503-1607-1615.pdf",
        "bytes": 215826
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr191014.pdf",
        "bytes": 381753
      }
    ]
  },
  {
    "date": "2018-09-10",
    "title": "Rule 701",
    "description": "§701 Authorized Duties. Summary report sent: September 10, 2018. Legislative Oversight Committee report: N/A. Effective November 20, 2018.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi701.pdf",
        "bytes": 101644
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr180910.pdf",
        "bytes": 163165
      }
    ]
  },
  {
    "date": "2018-05-08",
    "title": "Rule 1511",
    "description": "§1511 Required Facilities, Personnel and Equipment for Sedation Procedures. Summary report sent: May 8, 2018. Legislative Oversight Committee report: N/A. Effective June 20, 2018.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi1511.pdf",
        "bytes": 95771
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr180508.pdf",
        "bytes": 135412
      }
    ]
  },
  {
    "date": "2017-11-09",
    "title": "Rules 134, 306, 706, 1505, 1607, 1611, 1613, 1709, 1711",
    "description": "§134 Prescription Monitoring Program; §306 Requirements of Applicants for Dental Licensure by Credentials; §706 Requirements of Applicants for Licensure by Credentials (Hygienists); §1505 Personal Permit Renewals; §1607 Exemptions; §1611 Continuing Education Requirements for Relicensure of Dentists; §1613 Continuing Education Requirements for Relicensure of Dentists; §1709 Examination of Dentists; §1711 Examination of Hygienists. Summary report sent: November 9, 2017. Legislative Oversight Committee report: N/A. Effective January 20, 2018.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi134-306-706-1505-1607-1611-1613-1709-1711.pdf",
        "bytes": 156196
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr171109.pdf",
        "bytes": 220349
      }
    ]
  },
  {
    "date": "2017-07-11",
    "title": "Rules 122, 128, 301, 411, 1511",
    "description": "§122 Scopes of Practice; §128 Provisional Licensure for Dental Healthcare Workers Providing Gratuitous Services; §301 Advertising and Soliciting by Dentists; §411 Miscellaneous Fees and Costs; §1511 Required facilities, Personnel and Equipment for Sedation Procedures. Summary report sent: July 11, 2017. Legislative Oversight Committee report: N/A. Effective September 20, 2017.",
    "documents": [
      {
        "label": "Notice of Intent",
        "href": "/documents/rulemaking/noi122-128-301-411-1511.pdf",
        "bytes": 114031
      },
      {
        "label": "Summary Report",
        "href": "/documents/rulemaking/sr170711.pdf",
        "bytes": 122984
      }
    ]
  }
];

export const RULEMAKING_YEARLY_REPORTS: { year: number; title: string; href: string; bytes: number }[] = [
  {
    "year": 2024,
    "title": "2024 Yearly Report",
    "href": "/documents/rulemaking/2024report.pdf",
    "bytes": 433674
  },
  {
    "year": 2023,
    "title": "2023 Yearly Report",
    "href": "/documents/rulemaking/2023report.pdf",
    "bytes": 543940
  },
  {
    "year": 2022,
    "title": "2022 Yearly Report",
    "href": "/documents/rulemaking/2022report.pdf",
    "bytes": 439611
  },
  {
    "year": 2021,
    "title": "2021 Yearly Report",
    "href": "/documents/rulemaking/2021report.pdf",
    "bytes": 447335
  },
  {
    "year": 2020,
    "title": "2020 Yearly Report",
    "href": "/documents/rulemaking/2020report.pdf",
    "bytes": 109319
  }
];

export const SITE_DOCUMENTS = {
  "complaint_form": {
    "label": "Complaint Form",
    "href": "/documents/forms/complaintform.pdf",
    "bytes": 172538
  },
  "dental_practice_act": {
    "label": "Dental Practice Act",
    "href": "/documents/applications/dentalpracticeact.pdf",
    "bytes": 414846
  },
  "board_rules": {
    "label": "Board Rules: Title 46 Professional and Occupational Standards, Part XXXIII - Dental Health Professions",
    "href": "/documents/applications/46v33.pdf",
    "bytes": 823655
  },
  "sexual_harassment_policy": {
    "label": "Louisiana State Board of Dentistry Sexual Harassment Policy",
    "href": "/documents/forms/sexualharassmentpolicy.pdf",
    "bytes": 129105
  },
  "ada_policy": {
    "label": "Louisiana State Board of Dentistry ADA Policy",
    "href": "/documents/forms/adapolicy.pdf",
    "bytes": 204213
  },
  "ce_broker_common_problems": {
    "label": "Most common reasons your CE Broker transcript may not be correct",
    "href": "/documents/forms/cebcommonproblems.pdf",
    "bytes": 371696
  },
  "opioid_ce_exemption_affidavit": {
    "label": "Affidavit for Opioid Management CE Exemption (dentists only)",
    "href": "/documents/forms/affidavitnocds.pdf",
    "bytes": 111369
  },
  "edda_application": {
    "label": "EDDA Application",
    "href": "/documents/applications/edda-application.pdf",
    "bytes": 160875
  }
} as const satisfies Record<string, DocumentLink>;
