// Mock data for public UI development. This will be replaced with real DB queries later.

export const MOCK_ALERTS = [
  {
    id: 1,
    title: "2026 License Renewal Deadline",
    content:
      "All dental and dental hygiene licenses expire on December 31, 2026. Renewal applications are available through the online portal. Late renewals are subject to additional fees.",
    severity: "warning" as const,
    isActive: true,
    startsAt: "2026-01-01T00:00:00Z",
    endsAt: "2026-12-31T23:59:59Z",
    sortOrder: 0,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: 2,
    title: "Updated Opioid Management CE Requirements",
    content:
      "Effective January 1, 2026, all dentists and dental hygienists must complete three (3) hours of opioid management continuing education as part of their annual CE requirements. See Resources for approved courses.",
    severity: "info" as const,
    isActive: true,
    startsAt: "2026-01-01T00:00:00Z",
    endsAt: null,
    sortOrder: 1,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_POSTS = [
  {
    id: 1,
    title: "Board Approves Revised Anesthesia Permit Requirements",
    slug: "revised-anesthesia-permit-requirements-2026",
    content: `<p>The Louisiana State Board of Dentistry has approved revised requirements for dental anesthesia permits, effective July 1, 2026. These changes reflect updated safety standards and align with recommendations from the American Dental Association.</p><h2>Key Changes</h2><ul><li>Minimum facility inspection requirements have been updated to include new emergency equipment standards</li><li>Continuing education requirements for permit holders have been increased to 8 hours annually</li><li>A new supervised clinical experience pathway has been established for initial permit applicants</li></ul><p>All current permit holders will receive written notification of the changes. The Board encourages practitioners to review the updated rules, available on the Laws &amp; Rules page.</p>`,
    excerpt:
      "The Board has approved updated anesthesia permit requirements effective July 1, 2026, including new facility standards and CE requirements.",
    featuredImage: null,
    status: "published" as const,
    publishedAt: "2026-02-15T10:00:00Z",
    authorId: 1,
    createdAt: "2026-02-14T08:00:00Z",
    updatedAt: "2026-02-15T10:00:00Z",
  },
  {
    id: 2,
    title: "CE Broker Integration Now Available for Louisiana Licensees",
    slug: "ce-broker-integration-available",
    content: `<p>The Louisiana State Board of Dentistry is pleased to announce the integration of CE Broker for tracking continuing education credits. All Louisiana-licensed dentists and dental hygienists can now use CE Broker to manage and report their CE compliance electronically.</p><h2>Getting Started</h2><p>Visit <a href="https://cebroker.com">cebroker.com</a> to create your free account and link your Louisiana license. Your existing CE records will be automatically imported where available.</p><p>This integration streamlines the audit process and provides real-time compliance tracking for licensees.</p>`,
    excerpt:
      "CE Broker is now integrated with the Board for electronic CE tracking. Create your free account today.",
    featuredImage: null,
    status: "published" as const,
    publishedAt: "2026-02-01T09:00:00Z",
    authorId: 1,
    createdAt: "2026-01-30T08:00:00Z",
    updatedAt: "2026-02-01T09:00:00Z",
  },
  {
    id: 3,
    title: "March 2026 Board Meeting Scheduled",
    slug: "march-2026-board-meeting",
    content: `<p>The next regular meeting of the Louisiana State Board of Dentistry will be held on Friday, March 20, 2026, beginning at 9:00 AM in the Board's offices at 18212 East Petroleum Drive, Suite 2-B, Baton Rouge, Louisiana 70809.</p><p>The agenda will be posted at least 24 hours in advance of the meeting in accordance with the Louisiana Open Meetings Law. Members of the public are welcome to attend.</p>`,
    excerpt:
      "The next Board meeting is scheduled for March 20, 2026, at 9:00 AM at the Board offices in Baton Rouge.",
    featuredImage: null,
    status: "published" as const,
    publishedAt: "2026-01-20T08:00:00Z",
    authorId: 1,
    createdAt: "2026-01-19T08:00:00Z",
    updatedAt: "2026-01-20T08:00:00Z",
  },
  {
    id: 4,
    title: "Reminder: BLS Certification Required for All Licensees",
    slug: "bls-certification-reminder",
    content: `<p>The Louisiana State Board of Dentistry reminds all licensed dentists and dental hygienists that a current Basic Life Support (BLS) certification is required for active licensure. BLS certification must be from an approved provider and must remain current throughout the license period.</p><p>Failure to maintain current BLS certification may result in disciplinary action. Contact the Board office if you have questions about approved BLS providers.</p>`,
    excerpt:
      "All licensed dentists and hygienists must maintain current BLS certification for active licensure.",
    featuredImage: null,
    status: "published" as const,
    publishedAt: "2026-01-10T08:00:00Z",
    authorId: 1,
    createdAt: "2026-01-09T08:00:00Z",
    updatedAt: "2026-01-10T08:00:00Z",
  },
];

export const MOCK_MEETINGS = [
  {
    id: 1,
    title: "Regular Board Meeting",
    meetingDate: "2026-03-20T14:00:00Z",
    description:
      "Regular meeting of the Louisiana State Board of Dentistry. Open to the public.",
    meetingType: "board",
    isPublished: true,
    documents: [
      {
        id: 1,
        meetingId: 1,
        docType: "notice" as const,
        title: "Public Notice - March 2026 Meeting",
        blobUrl: "#",
        blobPathname: "meetings/2026/march-notice.pdf",
        fileSizeBytes: 245000,
        uploadedAt: "2026-02-20T08:00:00Z",
      },
      {
        id: 2,
        meetingId: 1,
        docType: "agenda" as const,
        title: "Agenda - March 2026 Meeting",
        blobUrl: "#",
        blobPathname: "meetings/2026/march-agenda.pdf",
        fileSizeBytes: 180000,
        uploadedAt: "2026-03-18T08:00:00Z",
      },
    ],
  },
  {
    id: 2,
    title: "Disciplinary Oversight Committee Meeting",
    meetingDate: "2026-04-10T14:00:00Z",
    description: "Disciplinary Oversight Committee meeting to review pending cases.",
    meetingType: "disciplinary",
    isPublished: true,
    documents: [],
  },
  {
    id: 3,
    title: "Regular Board Meeting",
    meetingDate: "2026-05-16T14:00:00Z",
    description: "Regular meeting of the Louisiana State Board of Dentistry.",
    meetingType: "board",
    isPublished: true,
    documents: [],
  },
  {
    id: 4,
    title: "Regular Board Meeting - January 2026",
    meetingDate: "2026-01-17T14:00:00Z",
    description: "Regular January meeting of the Louisiana State Board of Dentistry.",
    meetingType: "board",
    isPublished: true,
    documents: [
      {
        id: 3,
        meetingId: 4,
        docType: "notice" as const,
        title: "Public Notice - January 2026",
        blobUrl: "#",
        blobPathname: "meetings/2026/jan-notice.pdf",
        fileSizeBytes: 198000,
        uploadedAt: "2025-12-15T08:00:00Z",
      },
      {
        id: 4,
        meetingId: 4,
        docType: "agenda" as const,
        title: "Agenda - January 2026",
        blobUrl: "#",
        blobPathname: "meetings/2026/jan-agenda.pdf",
        fileSizeBytes: 215000,
        uploadedAt: "2026-01-15T08:00:00Z",
      },
      {
        id: 5,
        meetingId: 4,
        docType: "minutes" as const,
        title: "Minutes - January 2026",
        blobUrl: "#",
        blobPathname: "meetings/2026/jan-minutes.pdf",
        fileSizeBytes: 340000,
        uploadedAt: "2026-02-01T08:00:00Z",
      },
    ],
  },
];

export const MOCK_BOARD_MEMBERS = [
  {
    id: 1,
    name: "Robert Barsley",
    honorific: "Dr.",
    credential: "DDS, JD",
    role: "president" as const,
    district: "6th District",
    imageUrl: null,
    isActive: true,
    sortOrder: 0,
  },
  {
    id: 2,
    name: "Marija LaSalle",
    honorific: "Dr.",
    credential: "DDS",
    role: "vice_president" as const,
    district: "5th District",
    imageUrl: null,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 3,
    name: "Claudia Cavallino",
    honorific: "Dr.",
    credential: "DDS",
    role: "secretary_treasurer" as const,
    district: "1st District",
    imageUrl: null,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 4,
    name: "Thomas Price",
    honorific: "Dr.",
    credential: "DDS",
    role: "member" as const,
    district: "2nd District",
    imageUrl: null,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 5,
    name: "Glenn Dubroc",
    honorific: "Dr.",
    credential: "DDS",
    role: "member" as const,
    district: "3rd District",
    imageUrl: null,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 6,
    name: "Courtney Richey",
    honorific: "Dr.",
    credential: "DDS",
    role: "member" as const,
    district: "4th District",
    imageUrl: null,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 7,
    name: "Susan Thibodeaux",
    honorific: "",
    credential: "RDH",
    role: "hygienist_representative" as const,
    district: null,
    imageUrl: null,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 8,
    name: "Russell Marks",
    honorific: "Mr.",
    credential: null,
    role: "consumer_member" as const,
    district: null,
    imageUrl: null,
    isActive: true,
    sortOrder: 7,
  },
];

export const MOCK_STAFF = [
  {
    id: 1,
    name: "Arthur Hickham",
    title: "Executive Director",
    email: "ahickham@lsbd.org",
    phone: "225-219-7330",
    responsibilities:
      "Oversees all Board operations, enforcement, and administration.",
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 2,
    name: "Leah Hebert",
    title: "Director of Licensing",
    email: "lhebert@lsbd.org",
    phone: "225-219-7330",
    responsibilities:
      "Manages all licensing applications, renewals, and permit processing.",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 3,
    name: "Jennifer Perez",
    title: "Administrative Coordinator",
    email: "jperez@lsbd.org",
    phone: "225-219-7330",
    responsibilities:
      "Meeting coordination, records management, and public inquiries.",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 4,
    name: "Monica Boudreaux",
    title: "Investigator",
    email: "mboudreaux@lsbd.org",
    phone: "225-219-7330",
    responsibilities:
      "Investigates complaints and conducts inspections of dental facilities.",
    sortOrder: 3,
    isActive: true,
  },
];

export const MOCK_FEES_DENTIST = [
  { id: 1, category: "dentist" as const, name: "Licensure by Examination (LBE)", amount: 30000, description: "Initial license by clinical examination", sortOrder: 0, isActive: true },
  { id: 2, category: "dentist" as const, name: "Licensure by Credentials (LBC)", amount: 50000, description: "Initial license by credentials review", sortOrder: 1, isActive: true },
  { id: 3, category: "dentist" as const, name: "Annual License Renewal", amount: 27500, description: "Due annually by December 31", sortOrder: 2, isActive: true },
  { id: 4, category: "dentist" as const, name: "Late Renewal Penalty", amount: 15000, description: "Applied to renewals received after December 31", sortOrder: 3, isActive: true },
  { id: 5, category: "dentist" as const, name: "License Reinstatement", amount: 50000, description: "Reinstatement of expired or surrendered license", sortOrder: 4, isActive: true },
  { id: 6, category: "dentist" as const, name: "Volunteer License", amount: 0, description: "No fee for volunteer license", sortOrder: 5, isActive: true },
  { id: 7, category: "dentist" as const, name: "Duplicate License Certificate", amount: 2500, description: "Replacement certificate", sortOrder: 6, isActive: true },
  { id: 8, category: "dentist" as const, name: "General Anesthesia Permit", amount: 30000, description: "Annual permit fee", sortOrder: 7, isActive: true },
  { id: 9, category: "dentist" as const, name: "Parenteral Conscious Sedation Permit", amount: 30000, description: "Annual permit fee", sortOrder: 8, isActive: true },
];

export const MOCK_FEES_HYGIENIST = [
  { id: 10, category: "hygienist" as const, name: "Licensure by Examination (LBE)", amount: 15000, description: "Initial license by clinical examination", sortOrder: 0, isActive: true },
  { id: 11, category: "hygienist" as const, name: "Licensure by Credentials (LBC)", amount: 25000, description: "Initial license by credentials review", sortOrder: 1, isActive: true },
  { id: 12, category: "hygienist" as const, name: "Annual License Renewal", amount: 15000, description: "Due annually by December 31", sortOrder: 2, isActive: true },
  { id: 13, category: "hygienist" as const, name: "Late Renewal Penalty", amount: 10000, description: "Applied to renewals received after December 31", sortOrder: 3, isActive: true },
  { id: 14, category: "hygienist" as const, name: "License Reinstatement", amount: 25000, description: "Reinstatement of expired or surrendered license", sortOrder: 4, isActive: true },
  { id: 15, category: "hygienist" as const, name: "Local Anesthesia Permit", amount: 5000, description: "Annual permit for administration of local anesthesia", sortOrder: 5, isActive: true },
  { id: 16, category: "hygienist" as const, name: "Nitrous Oxide Permit", amount: 5000, description: "Annual permit for monitoring nitrous oxide", sortOrder: 6, isActive: true },
];

export const MOCK_FEES_MISC = [
  { id: 17, category: "miscellaneous" as const, name: "License Verification Letter", amount: 2500, description: "Written verification sent to another state board", sortOrder: 0, isActive: true },
  { id: 18, category: "miscellaneous" as const, name: "Certified Copy of Record", amount: 2500, description: "Per document", sortOrder: 1, isActive: true },
  { id: 19, category: "miscellaneous" as const, name: "Returned Check Fee", amount: 5000, description: "Fee for returned checks", sortOrder: 2, isActive: true },
];

export const MOCK_FORMS = [
  { id: 1, name: "Change of Address/Name/Email Form", description: "Notify the Board of changes to your personal information", category: "change_of_info", blobUrl: "#", fileSizeBytes: 124000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 2, name: "General Anesthesia Permit Application", description: "Application for initial general anesthesia permit", category: "dental_anesthesia", blobUrl: "#", fileSizeBytes: 356000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 3, name: "Parenteral Conscious Sedation Permit Application", description: "Application for parenteral conscious sedation permit", category: "dental_anesthesia", blobUrl: "#", fileSizeBytes: 312000, isExternal: false, externalUrl: null, sortOrder: 1, isActive: true },
  { id: 4, name: "Dental Hygiene Local Anesthesia Permit Application", description: "Application for dental hygienists to administer local anesthesia", category: "hygiene_anesthesia", blobUrl: "#", fileSizeBytes: 198000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 5, name: "Dental Hygiene Nitrous Oxide Monitoring Permit", description: "Application for monitoring nitrous oxide analgesia", category: "hygiene_anesthesia", blobUrl: "#", fileSizeBytes: 187000, isExternal: false, externalUrl: null, sortOrder: 1, isActive: true },
  { id: 6, name: "Mobile Dental Facility Registration", description: "Registration for mobile or portable dental offices", category: "mobile_portable", blobUrl: "#", fileSizeBytes: 276000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 7, name: "Opioid Management CE Exemption Request", description: "Request exemption from annual opioid management CE requirement", category: "opioid", blobUrl: "#", fileSizeBytes: 98000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 8, name: "CDC Dental Office Inspection Checklist", description: "Self-inspection checklist based on CDC infection control guidelines", category: "cdc_inspection", blobUrl: "#", fileSizeBytes: 430000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 9, name: "Controlled Substances Registration Application", description: "Application for DEA controlled substances registration", category: "controlled_substances", blobUrl: null, fileSizeBytes: null, isExternal: true, externalUrl: "https://www.deadiversion.usdoj.gov/", sortOrder: 0, isActive: true },
  { id: 10, name: "EDDA Certification Application", description: "Application for Expanded Duty Dental Assistant certification", category: "additional", blobUrl: "#", fileSizeBytes: 234000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
  { id: 11, name: "Complaint Form", description: "File a complaint against a licensed dental professional", category: "miscellaneous", blobUrl: "#", fileSizeBytes: 156000, isExternal: false, externalUrl: null, sortOrder: 0, isActive: true },
];

export const MOCK_PUBLICATIONS = [
  { id: 1, title: "The Bulletin - Winter 2026", year: 2026, description: "Winter 2026 edition of The Bulletin, the official newsletter of the Louisiana State Board of Dentistry.", blobUrl: "#", blobPathname: "publications/bulletin-winter-2026.pdf", fileSizeBytes: 2100000, isPublished: true },
  { id: 2, title: "The Bulletin - Fall 2025", year: 2025, description: "Fall 2025 edition featuring updated CE requirements and Board meeting summaries.", blobUrl: "#", blobPathname: "publications/bulletin-fall-2025.pdf", fileSizeBytes: 1890000, isPublished: true },
  { id: 3, title: "The Bulletin - Summer 2025", year: 2025, description: "Summer 2025 edition with anesthesia permit updates and disciplinary actions.", blobUrl: "#", blobPathname: "publications/bulletin-summer-2025.pdf", fileSizeBytes: 1760000, isPublished: true },
  { id: 4, title: "The Bulletin - Spring 2025", year: 2025, description: "Spring 2025 edition covering renewal reminders and legislative updates.", blobUrl: "#", blobPathname: "publications/bulletin-spring-2025.pdf", fileSizeBytes: 1650000, isPublished: true },
];
