<#
.SYNOPSIS
  Installs the LSBD sync Scheduled Tasks (run elevated; idempotent).

.DESCRIPTION
  1. Creates C:\ProgramData\lsbd-sync\ (+ logs\), copies the secrets file there
     (only if absent, or always with -RefreshSecrets) and locks it to
     SYSTEM:F + Administrators:F. The source file is left in place.
  2. Registers the Application event-log source LSBD-Sync.
  3. Writes the task wrapper C:\ProgramData\lsbd-sync\run-task.ps1 (outside git;
     the folder is admin-only because SYSTEM executes this file).
  4. Unregisters + re-registers, all as SYSTEM, working dir = release worktree:
       LSBD Sync Quick    every 15 min, 07:00-19:00, Mon-Fri   (20 min limit)
       LSBD Sync Weekend  hourly,       07:00-19:00, Sat-Sun   (20 min limit)
       LSBD Sync Full     daily 02:00: run.ts --mode full, then reconcile (60 min)
  5. ACLs C:\ProgramData\lsbd-sync (no inheritance; SYSTEM:F, Administrators:F)
     and its app\ subtree (additionally Users:RX, read-only for non-admins).

  Deploy code first with release.ps1. Tasks run ONLY from the release worktree.
  Logs: C:\ProgramData\lsbd-sync\logs\<task>-<yyyyMMdd-HHmm>.log (30 day retention).

  Integration tests: run pause-tasks.ps1 -Pause before `npm run test:it`,
  and -Resume afterwards.

  Optional healthcheck: add SYNC_HEALTHCHECK_URL=... to
  C:\ProgramData\lsbd-sync\secrets.env (a comment marks the spot).
#>
param(
  [switch]$RefreshSecrets
)

$ErrorActionPreference = 'Stop'

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
  throw 'install-task.ps1 must be run elevated (Administrator).'
}

$root     = 'C:\ProgramData\lsbd-sync'
$app      = Join-Path $root 'app'
$logs     = Join-Path $root 'logs'
$secrets  = Join-Path $root 'secrets.env'
$wrapper  = Join-Path $root 'run-task.ps1'
$fallback = 'C:\Users\Administrator\.lsbd-secrets.env'
$node     = 'C:\Program Files\nodejs\node.exe'
$tsxCli   = Join-Path $app 'node_modules\tsx\dist\cli.mjs'

if (-not (Test-Path $node))   { throw "Node not found at $node" }
if (-not (Test-Path $tsxCli)) { throw "Release worktree not deployed ($tsxCli missing). Run release.ps1 first." }

# --- 1. folders + secrets -------------------------------------------------
New-Item -ItemType Directory -Force -Path $root, $logs | Out-Null

if ((-not (Test-Path $secrets)) -or $RefreshSecrets) {
  if (-not (Test-Path $fallback)) { throw "No secrets source at $fallback" }
  # The file may already be locked to admins; take care with overwrite.
  Copy-Item -Path $fallback -Destination $secrets -Force
  Write-Host "Copied secrets file to $secrets"
} else {
  Write-Host "Secrets already at $secrets (use -RefreshSecrets to overwrite)."
}

$text = [IO.File]::ReadAllText($secrets)
if ($text -notmatch 'SYNC_HEALTHCHECK_URL') {
  $note = "`r`n# --- Optional: dead-man's-switch ping, called by scripts/sync/run.ts after each run.`r`n" +
          "# Add your healthcheck URL on the next line (remove the leading #), no quotes:`r`n" +
          "# SYNC_HEALTHCHECK_URL=https://hc-ping.com/your-uuid`r`n"
  if (-not $text.EndsWith("`n")) { $note = "`r`n" + $note }
  [IO.File]::AppendAllText($secrets, $note, (New-Object Text.UTF8Encoding($false)))
  Write-Host 'Added SYNC_HEALTHCHECK_URL placeholder comment to secrets file.'
}

# --- 2. event source ------------------------------------------------------
try {
  New-EventLog -LogName Application -Source 'LSBD-Sync' -ErrorAction Stop
  Write-Host 'Registered event source LSBD-Sync.'
} catch {
  if ($_.Exception.Message -match 'already registered') { Write-Host 'Event source LSBD-Sync already registered.' }
  else { throw }
}

# --- 3. wrapper (embedded; runs as SYSTEM) ---------------------------------
$wrapperText = @'
# Task wrapper for the LSBD sync. Generated by install-task.ps1; do not edit here.
# Logs only what the runner/reconcile print (redacted: counts and table names).
param([Parameter(Mandatory = $true)][ValidateSet('quick', 'weekend', 'full')][string]$Task)

$ErrorActionPreference = 'Continue'
$root = 'C:\ProgramData\lsbd-sync'
$app  = Join-Path $root 'app'
$logs = Join-Path $root 'logs'
$node = 'C:\Program Files\nodejs\node.exe'
$tsx  = Join-Path $app 'node_modules\tsx\dist\cli.mjs'
$utf8 = New-Object Text.UTF8Encoding($false)

New-Item -ItemType Directory -Force -Path $logs | Out-Null
Get-ChildItem -Path $logs -Filter '*.log' -ErrorAction SilentlyContinue |
  Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-30) } |
  Remove-Item -Force -ErrorAction SilentlyContinue

$log = Join-Path $logs ('{0}-{1}.log' -f $Task, (Get-Date -Format 'yyyyMMdd-HHmm'))
Set-Location $app

function Write-Log([string]$s) { [IO.File]::AppendAllText($log, $s + "`r`n", $utf8) }

function Invoke-Step([string]$Label, [string[]]$ScriptArgs) {
  Write-Log ("=== {0} start {1}" -f $Label, (Get-Date -Format 's'))
  $o = [IO.Path]::GetTempFileName(); $e = [IO.Path]::GetTempFileName()
  try {
    $argList = '"' + $tsx + '" ' + ($ScriptArgs -join ' ')
    $p = Start-Process -FilePath $node -ArgumentList $argList -WorkingDirectory $app `
           -NoNewWindow -Wait -PassThru -RedirectStandardOutput $o -RedirectStandardError $e
    $code = $p.ExitCode
    Write-Log '--- stdout'; Write-Log ([IO.File]::ReadAllText($o))
    Write-Log '--- stderr'; Write-Log ([IO.File]::ReadAllText($e))
  } finally {
    Remove-Item $o, $e -Force -ErrorAction SilentlyContinue
  }
  Write-Log ("=== {0} exit={1} end {2}" -f $Label, $code, (Get-Date -Format 's'))
  return $code
}

if ($Task -eq 'full') {
  $syncCode  = Invoke-Step 'sync --mode full' @('scripts\sync\run.ts', '--mode', 'full')
  # Reconcile runs even when the sync exited 2 (blocked) or 1 (failed).
  $reconCode = Invoke-Step 'reconcile' @('scripts\sync\reconcile.ts')
  Write-Log ("SUMMARY sync_exit={0} reconcile_exit={1}" -f $syncCode, $reconCode)
  $final = [Math]::Max([int]$syncCode, [int]$reconCode)
} else {
  $final = [int](Invoke-Step 'sync --mode quick' @('scripts\sync\run.ts', '--mode', 'quick'))
  Write-Log ("SUMMARY sync_exit={0}" -f $final)
}
exit $final
'@
[IO.File]::WriteAllText($wrapper, $wrapperText, (New-Object Text.UTF8Encoding($false)))
Write-Host "Wrote $wrapper"

# --- 4. tasks ---------------------------------------------------------------
function New-RepeatingTrigger([string[]]$Days, [int]$Minutes) {
  $t = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $Days -At '07:00'
  $rep = (New-ScheduledTaskTrigger -Once -At '07:00' `
            -RepetitionInterval (New-TimeSpan -Minutes $Minutes) `
            -RepetitionDuration (New-TimeSpan -Hours 12)).Repetition
  $t.Repetition = $rep
  return $t
}

function Register-SyncTask([string]$Name, [string]$Key, $Trigger, [int]$LimitMinutes, [string]$Desc) {
  if (Get-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $Name -Confirm:$false
  }
  $arg = '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "{0}" -Task {1}' -f $wrapper, $Key
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument $arg -WorkingDirectory $app
  $settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew `
      -ExecutionTimeLimit (New-TimeSpan -Minutes $LimitMinutes) `
      -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  Register-ScheduledTask -TaskName $Name -Action $action -Trigger $Trigger -Settings $settings `
      -Principal $principal -Description $Desc | Out-Null
  Write-Host "Registered '$Name'"
}

Register-SyncTask 'LSBD Sync Quick' 'quick' `
  (New-RepeatingTrigger @('Monday','Tuesday','Wednesday','Thursday','Friday') 15) 20 `
  'LSBD MSSQL -> Supabase quick sync, every 15 min 07:00-19:00 Mon-Fri.'

Register-SyncTask 'LSBD Sync Weekend' 'weekend' `
  (New-RepeatingTrigger @('Saturday','Sunday') 60) 20 `
  'LSBD MSSQL -> Supabase quick sync, hourly 07:00-19:00 Sat-Sun.'

Register-SyncTask 'LSBD Sync Full' 'full' `
  (New-ScheduledTaskTrigger -Daily -At '02:00') 60 `
  'LSBD MSSQL -> Supabase full sync daily 02:00, then reconcile.'

# --- 5. ACLs ----------------------------------------------------------------
# Root: admin-only (holds secrets, logs and the SYSTEM-executed wrapper).
& icacls.exe $root /inheritance:r /grant:r '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-544:(OI)(CI)F' | Out-Null
if ($LASTEXITCODE -ne 0) { throw "icacls on $root failed ($LASTEXITCODE)" }
# Secrets file: explicit, no inheritance, SYSTEM + Administrators only.
& icacls.exe $secrets /inheritance:r /grant:r '*S-1-5-18:F' '*S-1-5-32-544:F' | Out-Null
if ($LASTEXITCODE -ne 0) { throw "icacls on $secrets failed ($LASTEXITCODE)" }
# App: code only; non-admins may read/execute but not modify.
& icacls.exe $app /inheritance:r /grant:r '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-544:(OI)(CI)F' '*S-1-5-32-545:(OI)(CI)RX' | Out-Null
if ($LASTEXITCODE -ne 0) { throw "icacls on $app failed ($LASTEXITCODE)" }

Get-ScheduledTask -TaskName 'LSBD Sync*' | ForEach-Object {
  '{0,-20} {1,-6} WorkingDir={2}' -f $_.TaskName, $_.State, $_.Actions[0].WorkingDirectory
}
