-- 0010_real_site_documents.sql
--
-- GENERATED by scripts/content/build-lsbd-org-import.mjs from content/lsbd-org/*.json.
-- Hand-applied, like 0005 (not in the Drizzle journal):
--   npx tsx scripts/apply-sql.ts drizzle/0010_real_site_documents.sql
--
-- Why: the bulletins, meetings and forms in the CMS were invented seed rows whose file
-- links were "#". This replaces them with what www.lsbd.org publishes (scraped
-- 2026-10-02). The PDFs are served by the site itself from public/documents/, so the
-- file columns hold site-relative paths.
--
-- APPLY AFTER (1) 0009_meetings_month_only.sql and (2) the deployment that contains
-- public/documents/ is live; before that the new links would 404.
--
-- RUNS ONCE: it deletes every row in publications, meetings (and their documents) and
-- downloadable_forms, so it refuses to run when real rows are already present.
-- No BEGIN/COMMIT: the runner wraps the file in a transaction.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.publications WHERE blob_url LIKE '/documents/%')
     OR EXISTS (SELECT 1 FROM public.meeting_documents WHERE blob_url LIKE '/documents/%')
     OR EXISTS (SELECT 1 FROM public.downloadable_forms WHERE blob_url LIKE '/documents/%') THEN
    RAISE EXCEPTION 'the lsbd.org documents are already imported; this file runs once';
  END IF;
END $$;

DELETE FROM public.meeting_documents;
DELETE FROM public.meetings;
DELETE FROM public.publications;
DELETE FROM public.downloadable_forms;

-- The Bulletin, one per year.
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2018', 2018, NULL, '/documents/bulletins/bulletin2018.pdf', 'documents/bulletins/bulletin2018.pdf', 540430, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2017', 2017, NULL, '/documents/bulletins/bulletin2017.pdf', 'documents/bulletins/bulletin2017.pdf', 409225, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2016', 2016, NULL, '/documents/bulletins/bulletin2016.pdf', 'documents/bulletins/bulletin2016.pdf', 681990, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2015', 2015, NULL, '/documents/bulletins/bulletin2015.pdf', 'documents/bulletins/bulletin2015.pdf', 659847, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2014', 2014, NULL, '/documents/bulletins/bulletin2014.pdf', 'documents/bulletins/bulletin2014.pdf', 762097, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2013', 2013, NULL, '/documents/bulletins/bulletin2013.pdf', 'documents/bulletins/bulletin2013.pdf', 1187804, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2012', 2012, NULL, '/documents/bulletins/bulletin2012.pdf', 'documents/bulletins/bulletin2012.pdf', 1105442, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2011', 2011, NULL, '/documents/bulletins/bulletin2011.pdf', 'documents/bulletins/bulletin2011.pdf', 1026269, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2010', 2010, NULL, '/documents/bulletins/bulletin2010.pdf', 'documents/bulletins/bulletin2010.pdf', 1017748, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2009', 2009, NULL, '/documents/bulletins/bulletin2009.pdf', 'documents/bulletins/bulletin2009.pdf', 780146, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2008', 2008, NULL, '/documents/bulletins/bulletin2008.pdf', 'documents/bulletins/bulletin2008.pdf', 338357, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2007', 2007, NULL, '/documents/bulletins/bulletin2007.pdf', 'documents/bulletins/bulletin2007.pdf', 1892295, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2006', 2006, NULL, '/documents/bulletins/bulletin2006.pdf', 'documents/bulletins/bulletin2006.pdf', 1826001, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2005', 2005, NULL, '/documents/bulletins/bulletin2005.pdf', 'documents/bulletins/bulletin2005.pdf', 1482655, true);
INSERT INTO public.publications (title, year, description, blob_url, blob_pathname, file_size_bytes, is_published) VALUES ('The Bulletin - 2004', 2004, NULL, '/documents/bulletins/bulletin2004.pdf', 'documents/bulletins/bulletin2004.pdf', 1801038, true);

-- Forms, applications and lists.
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Change of Mailing or Home Address', 'All dentists and hygienists are required to notify the board within 30 days of their change of mailing address.', 'change_of_info', '/documents/applications/mailinghomeaddress.pdf', 'documents/applications/mailinghomeaddress.pdf', 314401, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Change of Practice Location (dentists only)', 'All Louisiana dentists are required to notify the board of any changes of practice location within 30 days of the date of the change. If you add a new practice location, it will NOT automatically remove another location. You must submit one form to add a new practice location and a separate form to remove the former practice location. Notifying the board of your change of practice location will NOT change your official mailing address on file with the board.', 'change_of_info', '/documents/applications/practicelocation.pdf', 'documents/applications/practicelocation.pdf', 273076, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Change of Employer (hygienists only)', 'All Louisiana hygienists are required to notify the board of any changes in their employing dentist within 30 days of the date of the change. If you add a new employer to your record, it will NOT automatically remove another employer. You must submit one form to add a new employer and a separate form to remove the former employer. Notifying the board of your change of employer and practice location will NOT change your official mailing address on file with the board.', 'change_of_info', '/documents/applications/employerchange.pdf', 'documents/applications/employerchange.pdf', 271958, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Nitrous Oxide Personal Permit Application', 'The Board no longer issues office nitrous permits. A personal nitrous permit is all that is required to administer nitrous oxide.', 'dental_anesthesia', '/documents/applications/nitrous-oxide-application.pdf', 'documents/applications/nitrous-oxide-application.pdf', 231967, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Moderate Sedation Personal and Office Permit Application', NULL, 'dental_anesthesia', '/documents/applications/moderateapplication.pdf', 'documents/applications/moderateapplication.pdf', 419851, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('General Anesthesia Personal and Office Permit Application', NULL, 'dental_anesthesia', '/documents/applications/generalanesthesiaapplication.pdf', 'documents/applications/generalanesthesiaapplication.pdf', 420508, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Anesthesia Inspection Sheet', 'Office permits for any level of anesthesia other than nitrous oxide require an office inspection. Please use the following inspection sheet as a checklist to ensure you have the appropriate equipment and information available for the inspector.', 'dental_anesthesia', '/documents/forms/anesthesiainspection.pdf', 'documents/forms/anesthesiainspection.pdf', 127550, false, NULL, 40, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental Hygiene Nitrous Oxide Permit Application', NULL, 'hygiene_anesthesia', '/documents/applications/hygienenitrousoxideapplication.pdf', 'documents/applications/hygienenitrousoxideapplication.pdf', 249467, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental Hygiene Local Anesthesia Permit Application', NULL, 'hygiene_anesthesia', '/documents/applications/hygiene-anesthesia-application.pdf', 'documents/applications/hygiene-anesthesia-application.pdf', 385947, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Local Anesthesia Affidavit', 'If you have been licensed and permitted in another state to administer local anesthesia in your practice of dental hygiene, and you wish to apply for a permit to administer local anesthesia in Louisiana, please also fill out the affidavit and submit it with your local anesthesia permit application.', 'hygiene_anesthesia', '/documents/applications/local-anesthesia-affidavit.pdf', 'documents/applications/local-anesthesia-affidavit.pdf', 186292, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Mobile Dental Office Permit Application', 'A mobile office is a self-contained movable facility such as an RV. A mobile dental office permit will only be issued to a Louisiana licensed dentist.', 'mobile_portable', '/documents/forms/mobilepermit.pdf', 'documents/forms/mobilepermit.pdf', 286688, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Portable Dental Office Permit Application', 'A portable office consists of portable dental equipment which is set up on site. A portable dental office permit will only be issued to a Louisiana licensed dentist.', 'mobile_portable', '/documents/forms/portablepermit.pdf', 'documents/forms/portablepermit.pdf', 285458, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Affidavit for Opioid Management CE Exemption (dentists only)', 'Dentists who do not prescribe, dispense, or administer any controlled substances are not required to complete the 3 hours of opioid management continuing education. Complete this affidavit in the presence of a notary and mail it to the board office. We will then verify you have not prescribed, dispensed, or administered any controlled substances with the Prescription Monitoring Program. Should you prescribe, dispense, or administer controlled substances in the future, you will be required to obtain the opioid management CE.', 'opioid', '/documents/forms/affidavitnocds.pdf', 'documents/forms/affidavitnocds.pdf', 111369, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Sample Inspection Notice', 'This is an example of the notice a dentist should receive approximately one week prior to the scheduled CDC inspection.', 'cdc_inspection', '/documents/forms/inspectionnotice.pdf', 'documents/forms/inspectionnotice.pdf', 294061, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Inspection Form', 'The inspector will use this form when inspecting the dentist''s office. Please use the inspection sheet as a checklist so that the appropriate equipment and documentation is available for the inspector.', 'cdc_inspection', '/documents/forms/cdcinspection.pdf', 'documents/forms/cdcinspection.pdf', 215214, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('HBV Vaccine Declination', 'Dentists are required to offer certain personnel the Hepatitis B vaccine at no charge. The dentist should maintain information regarding the staff''s HBV vaccinations. If any employee refuses the HBV vaccine, a declination statement should be maintained in the dentist''s office. The declination form is an example of this statement.', 'cdc_inspection', '/documents/forms/hbvdeclination.pdf', 'documents/forms/hbvdeclination.pdf', 180225, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Sample Controlled Substances Log Form', 'All dentists are required to maintain an accurate running total of controlled substances in their possession. Please see the sample file for your convenience. This form should be maintained by the dentist. Do not submit this form to the board.', 'controlled_substances', '/documents/forms/controlledsubstanceslog.pdf', 'documents/forms/controlledsubstanceslog.pdf', 74536, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('EDDA Application', 'Expanded Duty Dental Assistants. You may apply for the EDDA certificate confirmation by submitting the EDDA application, a copy of your proof of completion of the EDDA course, BLS course, and radiology course along with the application fee of $100 to the Board office. DO NOT SEND CASH.', 'additional', '/documents/applications/edda-application.pdf', 'documents/applications/edda-application.pdf', 160875, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Expungement Application', 'Application for Expungement of First Time Advertising Violations', 'additional', '/documents/applications/expungementapplication.pdf', 'documents/applications/expungementapplication.pdf', 63281, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental Information Sheet', 'Newly licensed dentists only', 'miscellaneous', '/documents/forms/dentalinfo.pdf', 'documents/forms/dentalinfo.pdf', 265000, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Hygiene Information Sheet', 'Newly licensed hygienists only', 'miscellaneous', '/documents/forms/hygieneinfo.pdf', 'documents/forms/hygieneinfo.pdf', 220194, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('HIV/HBV/HCV Reporting Form', NULL, 'miscellaneous', '/documents/applications/hiv-hbv-hcvform.pdf', 'documents/applications/hiv-hbv-hcvform.pdf', 195924, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Approved Radiology Course List', NULL, 'miscellaneous', '/documents/applications/approvedradiology.pdf', 'documents/applications/approvedradiology.pdf', 80559, false, NULL, 40, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Complaint Form', 'To lodge a complaint against a licensee, please download the form, fill it out, and then return it to our office. You may email, fax, or mail it.', 'miscellaneous', '/documents/forms/complaintform.pdf', 'documents/forms/complaintform.pdf', 172538, false, NULL, 50, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental License by Examination (LBE) Application', 'You may qualify for a dental license by examination if you completed the ADEX examination within FIVE years of applying for a Louisiana license.', 'license_applications', '/documents/applications/lbeapplicationdental.pdf', 'documents/applications/lbeapplicationdental.pdf', 1453304, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental Hygiene License by Examination (LBE) Application', 'You may qualify for a dental hygiene license by examination if you completed the ADEX examination within THREE years of applying for a Louisiana license.', 'license_applications', '/documents/applications/lbeapplicationhygiene.pdf', 'documents/applications/lbeapplicationhygiene.pdf', 1448400, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental License by Credentials (LBC) Application', 'You may qualify for a regular dental license by credentials if you currently hold a license in another state and have practiced at least 1000 hours each year for the immediately preceding three years.', 'license_applications', '/documents/forms/dentallbc.pdf', 'documents/forms/dentallbc.pdf', 1757042, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental Hygiene License by Credentials (LBC) Application', 'You may qualify for a regular dental hygiene license by credentials if you currently hold a license in another state and have practiced at least 1000 hours for the immediately preceding year.', 'license_applications', '/documents/forms/hygienelbc.pdf', 'documents/forms/hygienelbc.pdf', 1641335, false, NULL, 40, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental License by Credentials (LBC) Application - Louisiana Residents', 'You must currently reside in Louisiana and hold a license in another state to use this application.', 'license_applications', '/documents/forms/dentallbc-la-resident.pdf', 'documents/forms/dentallbc-la-resident.pdf', 1477627, false, NULL, 50, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Dental Hygiene License by Credentials (LBC) Application - Louisiana Residents', 'You must reside in Louisiana and currently hold a license in another state to use this application.', 'license_applications', '/documents/forms/hygienelbc-la-resident.pdf', 'documents/forms/hygienelbc-la-resident.pdf', 1445412, false, NULL, 60, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('Restricted License Application', 'Restricted licenses are for dentists participating in postgraduate programs in Louisiana or instructors in Louisiana dental education.', 'license_applications', '/documents/forms/restrictedapplication.pdf', 'documents/forms/restrictedapplication.pdf', 369015, false, NULL, 70, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2023 dental licenses issued', 'Licenses issued, by parish. 2023 new dental licenses denied--0', 'license_statistics', '/documents/forms/2023newdental.pdf', 'documents/forms/2023newdental.pdf', 99489, false, NULL, 10, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2023 dental licenses renewed', 'Licenses renewed, by parish. 2023 dental license renewals denied--0', 'license_statistics', '/documents/forms/2023reneweddental.pdf', 'documents/forms/2023reneweddental.pdf', 115692, false, NULL, 20, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2023 dental hygiene licenses issued', 'Licenses issued, by parish. 2023 new dental hygiene licenses denied--0', 'license_statistics', '/documents/forms/2023newhygiene.pdf', 'documents/forms/2023newhygiene.pdf', 98109, false, NULL, 30, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2023 dental hygiene licenses renewed', 'Licenses renewed, by parish. 2023 dental hygiene license renewals denied--0', 'license_statistics', '/documents/forms/2023renewedhygiene.pdf', 'documents/forms/2023renewedhygiene.pdf', 108107, false, NULL, 40, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2024 dental licenses issued', 'Licenses issued, by parish. 2024 new dental licenses denied--0', 'license_statistics', '/documents/forms/2024newdental.pdf', 'documents/forms/2024newdental.pdf', 98333, false, NULL, 50, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2024 dental licenses renewed', 'Licenses renewed, by parish. 2024 dental license renewals denied--0', 'license_statistics', '/documents/forms/2024reneweddental.pdf', 'documents/forms/2024reneweddental.pdf', 112965, false, NULL, 60, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2024 dental hygiene licenses issued', 'Licenses issued, by parish. 2024 new dental hygiene licenses denied--0', 'license_statistics', '/documents/forms/2024newhygiene.pdf', 'documents/forms/2024newhygiene.pdf', 103063, false, NULL, 70, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2024 dental hygiene licenses renewed', 'Licenses renewed, by parish. 2024 dental hygiene license renewals denied--0', 'license_statistics', '/documents/forms/2024renewedhygiene.pdf', 'documents/forms/2024renewedhygiene.pdf', 107270, false, NULL, 80, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2025 dental licenses issued', 'Licenses issued, by parish. 2025 new dental licenses denied--0', 'license_statistics', '/documents/forms/2025newdental.pdf', 'documents/forms/2025newdental.pdf', 186963, false, NULL, 90, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2025 dental licenses renewed', 'Licenses renewed, by parish. 2025 dental license renewals denied--0', 'license_statistics', '/documents/forms/2025reneweddental.pdf', 'documents/forms/2025reneweddental.pdf', 205071, false, NULL, 100, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2025 dental hygiene licenses issued', 'Licenses issued, by parish. 2025 new dental hygiene licenses denied--0', 'license_statistics', '/documents/forms/2025newhygiene.pdf', 'documents/forms/2025newhygiene.pdf', 195458, false, NULL, 110, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('2025 dental hygiene licenses renewed', 'Licenses renewed, by parish. 2025 dental hygiene license renewals denied--0', 'license_statistics', '/documents/forms/2025renewedhygiene.pdf', 'documents/forms/2025renewedhygiene.pdf', 208593, false, NULL, 120, true);
INSERT INTO public.downloadable_forms (name, description, category, blob_url, blob_pathname, file_size_bytes, is_external, external_url, sort_order, is_active) VALUES ('DEA Forms', 'DEA 224 New Application or DEA 106 Theft or Loss Report', 'controlled_substances', NULL, NULL, NULL, true, 'https://www.deadiversion.usdoj.gov/online_forms.htm', 900, true);

-- Meetings and their documents.
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Disciplinary Oversight Committee Informal Conferences', '2026-08-14T18:00:00Z', NULL, 'disciplinary', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/26.8.14informalsnotice.pdf', 'documents/meetings/26.8.14informalsnotice.pdf', 707283),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/26.8.14informalsagenda.pdf', 'documents/meetings/26.8.14informalsagenda.pdf', 708695);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Office Management Committee Meeting', '2026-08-14T18:00:00Z', NULL, 'office_management', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/26.8.14omnotice.pdf', 'documents/meetings/26.8.14omnotice.pdf', 640285),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/26.8.14omagenda.pdf', 'documents/meetings/26.8.14omagenda.pdf', 505086);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2026-08-14T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/26.8.14notice.pdf', 'documents/meetings/26.8.14notice.pdf', 640601),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/26.8.14agenda.pdf', 'documents/meetings/26.8.14agenda.pdf', 606742);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2026-05-08T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/26.5.8notice.pdf', 'documents/meetings/26.5.8notice.pdf', 629214),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/26.5.8agenda.pdf', 'documents/meetings/26.5.8agenda.pdf', 759843),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/26.5.8minutes.pdf', 'documents/meetings/26.5.8minutes.pdf', 314380);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2026-03-20T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/26.3.20notice.pdf', 'documents/meetings/26.3.20notice.pdf', 629174),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/26.3.20agenda.pdf', 'documents/meetings/26.3.20agenda.pdf', 757913),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/26.3.20minutes.pdf', 'documents/meetings/26.3.20minutes.pdf', 315871);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2025-12-05T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/25.12.5notice.pdf', 'documents/meetings/25.12.5notice.pdf', 646539),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/25.12.5agenda.pdf', 'documents/meetings/25.12.5agenda.pdf', 641408),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/25.12.5minutes.pdf', 'documents/meetings/25.12.5minutes.pdf', 345230);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2025-08-15T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/25.8.15notice.pdf', 'documents/meetings/25.8.15notice.pdf', 665625),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/25.8.15agenda.pdf', 'documents/meetings/25.8.15agenda.pdf', 646737),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/25.8.15minutes.pdf', 'documents/meetings/25.8.15minutes.pdf', 328074);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2025-05-09T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/25.5.9notice.pdf', 'documents/meetings/25.5.9notice.pdf', 665022),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/25.5.9agenda.pdf', 'documents/meetings/25.5.9agenda.pdf', 803303),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/25.5.9minutes.pdf', 'documents/meetings/25.5.9minutes.pdf', 212345);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2025-03-21T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/25.3.21notice.pdf', 'documents/meetings/25.3.21notice.pdf', 665044),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/25.3.21agenda.pdf', 'documents/meetings/25.3.21agenda.pdf', 172142),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/25.3.21minutes.pdf', 'documents/meetings/25.3.21minutes.pdf', 211079);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2024-12-06T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/24.12.6notice.pdf', 'documents/meetings/24.12.6notice.pdf', 155017),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/24.12.6agenda.pdf', 'documents/meetings/24.12.6agenda.pdf', 111040),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/24.12.6minutes.pdf', 'documents/meetings/24.12.6minutes.pdf', 847842);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2024-08-16T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/24.8.16notice.pdf', 'documents/meetings/24.8.16notice.pdf', 251393),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/24.8.16agenda.pdf', 'documents/meetings/24.8.16agenda.pdf', 109198),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/24.8.16minutes.pdf', 'documents/meetings/24.8.16minutes.pdf', 211163);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2024-05-10T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/24.5.10notice.pdf', 'documents/meetings/24.5.10notice.pdf', 662208),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/24.5.10agenda.pdf', 'documents/meetings/24.5.10agenda.pdf', 151407),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/24.5.10minutes.pdf', 'documents/meetings/24.5.10minutes.pdf', 208332);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2024-03-08T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/24.3.8notice.pdf', 'documents/meetings/24.3.8notice.pdf', 254256),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/24.3.8agenda.pdf', 'documents/meetings/24.3.8agenda.pdf', 151001),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/24.3.8minutes.pdf', 'documents/meetings/24.3.8minutes.pdf', 215739);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2023-12-08T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/23.12.8notice.pdf', 'documents/meetings/23.12.8notice.pdf', 150620),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/23.12.8agenda.pdf', 'documents/meetings/23.12.8agenda.pdf', 106198),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/23.12.8minutes.pdf', 'documents/meetings/23.12.8minutes.pdf', 215723);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2023-08-18T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/23.8.18notice.pdf', 'documents/meetings/23.8.18notice.pdf', 150830),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/23.8.18agenda.pdf', 'documents/meetings/23.8.18agenda.pdf', 106150),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/23.8.18minutes.pdf', 'documents/meetings/23.8.18minutes.pdf', 218202);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2023-05-12T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/23.5.12notice.pdf', 'documents/meetings/23.5.12notice.pdf', 205183),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/23.5.12agenda.pdf', 'documents/meetings/23.5.12agenda.pdf', 174536),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/23.5.12minutes.pdf', 'documents/meetings/23.5.12minutes.pdf', 202569);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2023-03-10T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/23.3.10notice.pdf', 'documents/meetings/23.3.10notice.pdf', 186796),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/23.3.10agenda.pdf', 'documents/meetings/23.3.10agenda.pdf', 205911),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/23.3.10minutes.pdf', 'documents/meetings/23.3.10minutes.pdf', 212518);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2022-12-02T18:00:00Z', 'Page lists this meeting under the date range "December 2-3, 2022".', 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/22.12.2notice.pdf', 'documents/meetings/22.12.2notice.pdf', 187348),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/22.12.2agenda.pdf', 'documents/meetings/22.12.2agenda.pdf', 164989),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/22.12.2minutes.pdf', 'documents/meetings/22.12.2minutes.pdf', 222987);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2022-08-19T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/22.8.19notice.pdf', 'documents/meetings/22.8.19notice.pdf', 187081),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/22.8.19agenda.pdf', 'documents/meetings/22.8.19agenda.pdf', 168020),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/22.8.19minutes.pdf', 'documents/meetings/22.8.19minutes.pdf', 219786);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2022-05-06T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/22.5.6notice.pdf', 'documents/meetings/22.5.6notice.pdf', 651390),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/22.5.6agenda.pdf', 'documents/meetings/22.5.6agenda.pdf', 795666),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/22.5.6minutes.pdf', 'documents/meetings/22.5.6minutes.pdf', 209048);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2022-03-11T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/22.3.11notice.pdf', 'documents/meetings/22.3.11notice.pdf', 191451),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/22.3.11agenda.pdf', 'documents/meetings/22.3.11agenda.pdf', 211288),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/22.3.11minutes.pdf', 'documents/meetings/22.3.11minutes.pdf', 208062);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2021-12-10T18:00:00Z', 'Page lists this meeting under the date range "December 10-11, 2021".', 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/21.12.11notice.pdf', 'documents/meetings/21.12.11notice.pdf', 190304),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/21.12.11agenda.pdf', 'documents/meetings/21.12.11agenda.pdf', 169208),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/21.12.11minutes.pdf', 'documents/meetings/21.12.11minutes.pdf', 237313);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2021-09-28T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/21.9.28notice.pdf', 'documents/meetings/21.9.28notice.pdf', 189609),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/21.9.28agenda.pdf', 'documents/meetings/21.9.28agenda.pdf', 198352),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/21.9.28minutes.pdf', 'documents/meetings/21.9.28minutes.pdf', 173721);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2021-08-20T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/21.8.20notice.pdf', 'documents/meetings/21.8.20notice.pdf', 645106),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/21.8.20agenda.pdf', 'documents/meetings/21.8.20agenda.pdf', 531547);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2021-05-14T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/21.5.14notice.pdf', 'documents/meetings/21.5.14notice.pdf', 169969),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/21.5.14agenda.pdf', 'documents/meetings/21.5.14agenda.pdf', 43473),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/21.5.14minutes.pdf', 'documents/meetings/21.5.14minutes.pdf', 218707);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2021-03-05T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'notice', 'Public Notice', '/documents/meetings/21.3.5notice.pdf', 'documents/meetings/21.3.5notice.pdf', 170039),
  ((SELECT id FROM m), 'agenda', 'Agenda', '/documents/meetings/21.3.5agenda.pdf', 'documents/meetings/21.3.5agenda.pdf', 172352),
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/21.3.5minutes.pdf', 'documents/meetings/21.3.5minutes.pdf', 218495);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2020-12-05T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/20.12.5minutes.pdf', 'documents/meetings/20.12.5minutes.pdf', 212237);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2020-08-14T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/20.8.14minutes.pdf', 'documents/meetings/20.8.14minutes.pdf', 220992);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2020-07-10T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/20.7.10minutes.pdf', 'documents/meetings/20.7.10minutes.pdf', 207022);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2020-05-22T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/20.5.22minutes.pdf', 'documents/meetings/20.5.22minutes.pdf', 185942);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2020-05-15T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/20.5.15minutes.pdf', 'documents/meetings/20.5.15minutes.pdf', 192826);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2020-03-06T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/20.3.6minutes.pdf', 'documents/meetings/20.3.6minutes.pdf', 250615);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2019-12-06T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/19.12.6minutes.pdf', 'documents/meetings/19.12.6minutes.pdf', 232742);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2019-08-16T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/19.8.16minutes.pdf', 'documents/meetings/19.8.16minutes.pdf', 227782);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2019-05-17T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/19.5.17minutes.pdf', 'documents/meetings/19.5.17minutes.pdf', 248376);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2019-03-15T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/19.3.15minutes.pdf', 'documents/meetings/19.3.15minutes.pdf', 241042);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2018-12-01T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/18.12.1minutes.pdf', 'documents/meetings/18.12.1minutes.pdf', 394236);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2018-10-05T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/18.10.5minutes.pdf', 'documents/meetings/18.10.5minutes.pdf', 186536);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2018-08-17T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/18.8.17minutes.pdf', 'documents/meetings/18.8.17minutes.pdf', 231842);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2018-05-11T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/18.5.11minutes.pdf', 'documents/meetings/18.5.11minutes.pdf', 413094);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2018-02-23T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/18.2.23minutes.pdf', 'documents/meetings/18.2.23minutes.pdf', 385658);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2017-12-02T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/12217minutes.pdf', 'documents/meetings/12217minutes.pdf', 392637);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2017-08-18T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/81817minutes.pdf', 'documents/meetings/81817minutes.pdf', 411533);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2017-05-12T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/51217minutes.pdf', 'documents/meetings/51217minutes.pdf', 401885);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting', '2017-03-10T18:00:00Z', NULL, 'board', true, false) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutes31017.pdf', 'documents/meetings/minutes31017.pdf', 412799);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2016', '2016-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2016.pdf', 'documents/meetings/minutesdec2016.pdf', 408286);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2016', '2016-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2016.pdf', 'documents/meetings/minutesaug2016.pdf', 400851);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2016', '2016-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2016.pdf', 'documents/meetings/minutesmay2016.pdf', 403022);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - February 2016', '2016-02-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesfeb2016.pdf', 'documents/meetings/minutesfeb2016.pdf', 311372);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2015', '2015-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2015.pdf', 'documents/meetings/minutesdec2015.pdf', 338427);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2015', '2015-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2015.pdf', 'documents/meetings/minutesaug2015.pdf', 157256);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2015', '2015-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2015.pdf', 'documents/meetings/minutesmay2015.pdf', 246509);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - February 2015', '2015-02-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesfeb2015.pdf', 'documents/meetings/minutesfeb2015.pdf', 392548);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2014', '2014-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2014.pdf', 'documents/meetings/minutesdec2014.pdf', 242592);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2014', '2014-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2014.pdf', 'documents/meetings/minutesaug2014.pdf', 141065);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2014', '2014-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2014.pdf', 'documents/meetings/minutesmay2014.pdf', 126399);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - March 2014', '2014-03-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmarch2014.pdf', 'documents/meetings/minutesmarch2014.pdf', 235447);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2013', '2013-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2013.pdf', 'documents/meetings/minutesdec2013.pdf', 199278);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2013', '2013-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2013.pdf', 'documents/meetings/minutesaug2013.pdf', 207181);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2013', '2013-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2013.pdf', 'documents/meetings/minutesmay2013.pdf', 239728);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - March 2013', '2013-03-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmarch2013.pdf', 'documents/meetings/minutesmarch2013.pdf', 302854);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2012', '2012-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2012.pdf', 'documents/meetings/minutesdec2012.pdf', 98817);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2012', '2012-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2012.pdf', 'documents/meetings/minutesaug2012.pdf', 81651);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2012', '2012-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2012.pdf', 'documents/meetings/minutesmay2012.pdf', 393396);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - March 2012', '2012-03-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmarch2012.pdf', 'documents/meetings/minutesmarch2012.pdf', 72368);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2011', '2011-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2011.pdf', 'documents/meetings/minutesdec2011.pdf', 188094);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2011', '2011-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2011.pdf', 'documents/meetings/minutesaug2011.pdf', 110632);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2011', '2011-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2011.pdf', 'documents/meetings/minutesmay2011.pdf', 96774);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - February 2011', '2011-02-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesfeb2011.pdf', 'documents/meetings/minutesfeb2011.pdf', 66183);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - December 2010', '2010-12-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesdec2010.pdf', 'documents/meetings/minutesdec2010.pdf', 272705);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - August 2010', '2010-08-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesaug2010.pdf', 'documents/meetings/minutesaug2010.pdf', 112999);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - May 2010', '2010-05-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmay2010.pdf', 'documents/meetings/minutesmay2010.pdf', 52599);
WITH m AS (INSERT INTO public.meetings (title, meeting_date, description, meeting_type, is_published, date_is_month_only) VALUES ('Board Meeting - March 2010', '2010-03-01T18:00:00Z', NULL, 'board', true, true) RETURNING id)
INSERT INTO public.meeting_documents (meeting_id, doc_type, title, blob_url, blob_pathname, file_size_bytes) VALUES
  ((SELECT id FROM m), 'minutes', 'Minutes', '/documents/meetings/minutesmarch2010.pdf', 'documents/meetings/minutesmarch2010.pdf', 52665);

INSERT INTO public.audit_log (user_id, action, entity_type, entity_id, details)
VALUES (NULL, 'import', 'site_documents', NULL,
  '{"source": "www.lsbd.org", "scraped": "2026-10-02", "publications": 15, "forms": 44, "meetings": 73, "meetingDocuments": 121}'::jsonb);
